backend:
  name: git-gateway # https://github.com/netlify/netlify-cms
  branch: main # 要更新的分支(可选；默认为主分支)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "source/images/uploads" # 媒体文件将存储在图片/上载下的Repo中。
public_folder: "/images/uploads" # 上传的媒体的src属性将以/images/uploads开头。

site_url: https://www.myql.xyz # 网站网址
display_url: https://www.myql.xyz # 显示网址

locale: "zh_Hans" # 语言环境 https://github.com/netlify/netlify-cms/tree/master/packages/netlify-cms-locales/src

collections: # https://www.netlifycms.org/docs/configuration-options/#collections
  - name: "posts" # 在路由中使用，例如：/admin/collections/blog。
    label: "Post" # 在用户界面中使用
    folder: "source/_posts" # 存储文件的文件夹的路径。
    create: true # 允许用户在这个集合中创建新的文件。
    fields: # 每份文件的字段，通常是前面的内容。
      - {
          label: "顶部图",
          name: "banner_img",
          widget: "image",
          required: false,
        }
      - {
          label: "文章封面",
          name: "index_img",
          widget: "image",
          required: false,
        }
      - { label: "文章排序", name: "sticky", widget: "number", required: false }
      - { label: "标题", name: "title", widget: "string" }
      - {
          label: "发布日期",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD HH:mm:ss",
          dateFormat: "YYYY-MM-DD",
          timeFormat: "HH:mm:ss",
          required: false,
        }
      - {
          label: "更新日期",
          name: "updated",
          widget: "datetime",
          format: "YYYY-MM-DD HH:mm:ss",
          dateFormat: "YYYY-MM-DD",
          timeFormat: "HH:mm:ss",
          required: false,
        }
      - { label: "标签", name: "tags", widget: "list", required: false }
      - { label: "分类", name: "categories", widget: "list", required: false }
      - { label: "关键词", name: "keywords", widget: "list", required: false }
      - { label: "摘要", name: "excerpt", widget: "list", required: false }
      - { label: "内容", name: "body", widget: "markdown", required: false }
      - {
          label: "永久链接",
          name: "permalink",
          widget: "string",
          required: false,
        }
      - {
          label: "评论",
          name: "comments",
          widget: "boolean",
          default: true,
          required: false,
        }

  - name: "pages"
    label: "Pages"
    files:
      - file: "source/about/index.md"
        name: "about"
        label: "关于"
        fields:
          - { label: "标题", name: "title", widget: "string" }
          - { label: "内容", name: "body", widget: "markdown", required: false }
          - {
              label: "评论",
              name: "comments",
              widget: "boolean",
              default: true,
              required: false,
            }

 